First commit: v.0.0.1 - Standup completed: make packages/template as …
zeroasterisk/react-uniforms-widgets pull request #10
Opened 2016-10-20 05:15 UTC by TinaBryan

…react-cdk
@zeroasterisk  

*created the packages/react-template
*configured to run with storybook ( the button works! )

Please let me know if I need to make any changes.  
Thanks again for the opportunity!

2016-10-21 18:49 UTC, zeroasterisk requested changes

2016-10-21 18:49 UTC, zeroasterisk commented on packages/react-template/package.json
> +  "name": "react-template",
This looks great...

Can you tell me why it's named `react-template` vs `template`?

I believe there is no need to specify `react` because everything in this project will be both `react` and `uniforms` specific.

2016-10-21 18:49 UTC, zeroasterisk commented on packages/react-template/package.json
> +    "url": "https://github.com/you/repo.git"
Can you please update the URL?

2016-10-21 18:49 UTC, zeroasterisk commented on packages/react-template/src/tests/index.js
> +});
Looks good - did you run the tests by any chance?  `npm test`

2016-10-22 15:57 UTC, TinaBryan commented on packages/react-template/src/tests/index.js
> +});
Thanks for the guidance!  Test have now been run.  Resolving errors.

2016-10-22 16:07 UTC, TinaBryan commented on packages/react-template/package.json
> +    "url": "https://github.com/you/repo.git"
Updated.  Once everything is updated with the pull request, do I ```git push``` and then create a new pull request?

2016-10-25 02:52 UTC, zeroasterisk approved these changes

2016-10-25 02:53 UTC, merged

2016-10-25 02:53 UTC, zeroasterisk commented
lookin' good - thanks!

2016-10-25 03:54 UTC, zeroasterisk commented
![ss](https://puu.sh/rUI3u/28646d048a.png)
![ss](https://puu.sh/rUI4i/461a7b16d7.png)